import {
  Coffee,
  Utensils,
  Building2,
  Landmark,
  Building,
  Camera,
  Dumbbell,
  Gamepad2,
  Plane,
  Tent,
  Trees,
  ShoppingCart,
  Croissant,
  Waves,
  Mountain,
  Frame,
  Wine,
  BookOpen,
  Store,
  Clapperboard,
  Sparkles,
  Flower2,
  Music,
  BookMarked,
  Apple,
} from "lucide-react";

export const HOME_CATEGORIES = [
  {
    title: "Places to Eat",
    query: "restaurants",
    icon: Utensils,
    description: "Discover local favorites and hidden gems",
  },
  {
    title: "Popular Attractions",
    query: "tourist attractions",
    icon: Camera,
    description: "Explore must-visit spots and landmarks",
  },
  {
    title: "Parks & Nature",
    query: "parks",
    icon: Trees,
    description: "Find peaceful outdoor spaces to explore",
  },
] as const;

export const ALL_CATEGORIES = [
  {
    title: "Coffee Shops",
    query: "cafe",
    icon: Coffee,
    description: "Cozy spots for coffee and conversation",
  },
  {
    title: "Restaurants",
    query: "restaurant",
    icon: Utensils,
    description: "Local eateries and dining experiences",
  },
  {
    title: "Parks",
    query: "park",
    icon: Trees,
    description: "Green spaces and urban retreats",
  },
  {
    title: "Museums",
    query: "museum",
    icon: Building2,
    description: "Art, history, and cultural exhibits",
  },
  {
    title: "Historic Sites",
    query: "historic site",
    icon: Landmark,
    description: "Landmarks and heritage locations",
  },
  {
    title: "Hotels",
    query: "hotel",
    icon: Building,
    description: "Places to stay and unwind",
  },
  {
    title: "Shopping",
    query: "shopping mall",
    icon: ShoppingCart,
    description: "Markets, malls, and boutiques",
  },
  {
    title: "Entertainment",
    query: "entertainment venue",
    icon: Gamepad2,
    description: "Fun activities and entertainment venues",
  },
  {
    title: "Fitness",
    query: "gym",
    icon: Dumbbell,
    description: "Gyms and sports facilities",
  },
  {
    title: "Travel",
    query: "transit station",
    icon: Plane,
    description: "Transportation hubs and stations",
  },
  {
    title: "Outdoor Activities",
    query: "hiking trail",
    icon: Tent,
    description: "Adventure spots and hiking trails",
  },
  {
    title: "Bakeries",
    query: "bakery",
    icon: Croissant,
    description: "Fresh pastries and artisanal breads",
  },
  {
    title: "Beaches",
    query: "beach",
    icon: Waves,
    description: "Coastal spots and waterfronts",
  },
  {
    title: "Viewpoints",
    query: "scenic viewpoint",
    icon: Mountain,
    description: "Scenic overlooks and city views",
  },
  {
    title: "Art Galleries",
    query: "art gallery",
    icon: Frame,
    description: "Contemporary and fine art spaces",
  },
  {
    title: "Nightlife",
    query: "nightclub",
    icon: Wine,
    description: "Bars, clubs, and evening venues",
  },
  {
    title: "Libraries",
    query: "library",
    icon: BookOpen,
    description: "Public libraries and reading rooms",
  },
  {
    title: "Markets",
    query: "market",
    icon: Store,
    description: "Local markets and food halls",
  },
  {
    title: "Movie Theaters",
    query: "movie theater",
    icon: Clapperboard,
    description: "Cinema venues and theaters",
  },
  {
    title: "Spas",
    query: "spa",
    icon: Sparkles,
    description: "Relaxation and wellness centers",
  },
  {
    title: "Botanical Gardens",
    query: "botanical garden",
    icon: Flower2,
    description: "Plant collections and gardens",
  },
  {
    title: "Live Music",
    query: "live music venue",
    icon: Music,
    description: "Concert halls and performance spaces",
  },
  {
    title: "Bookstores",
    query: "bookstore",
    icon: BookMarked,
    description: "Independent and specialty book shops",
  },
  {
    title: "Farmers Markets",
    query: "farmers market",
    icon: Apple,
    description: "Fresh local produce and artisanal goods",
  },
] as const;
