import { Destination } from "@/types/destinations";

export const destinations: Destination[] = [
  {
    id: "eiffel-tower",
    category: "Landmarks",
    location: "Famous Monuments",
    image: "/destinations/eiffel-tower.jpg",
    rotation: -2,
    initialPosition: {
      desktop: { top: "15%", right: "5%" },
      tablet: { top: "15%", right: "2%" },
      largeDesktop: { top: "15%", right: "5%" },
      extraLargeDesktop: { top: "15%", right: "5%" },
    },
    size: {
      desktop: { width: "200px", height: "150px" },
      tablet: { width: "180px", height: "140px" },
      largeDesktop: { width: "220px", height: "165px" },
      extraLargeDesktop: { width: "250px", height: "185px" },
    },
    parallaxFactor: 0.16,
    zIndex: 2,
  },
  {
    id: "cafes",
    category: "Cafés",
    location: "Local Coffee Shops",
    image: "/destinations/cafe.jpg",
    rotation: 3,
    initialPosition: {
      desktop: { top: "45%", left: "5%" },
      tablet: { top: "40%", left: "2%" },
      largeDesktop: { top: "45%", left: "5%" },
      extraLargeDesktop: { top: "45%", left: "5%" },
    },
    size: {
      desktop: { width: "220px", height: "150px" },
      tablet: { width: "190px", height: "140px" },
      largeDesktop: { width: "240px", height: "165px" },
      extraLargeDesktop: { width: "270px", height: "185px" },
    },
    parallaxFactor: 0.24,
    zIndex: 1,
  },
  {
    id: "museums",
    category: "Museums",
    location: "Art Galleries",
    image: "/destinations/museum.jpg",
    rotation: -2.5,
    initialPosition: {
      desktop: { top: "18%", left: "5%" },
      tablet: { top: "18%", left: "2%" },
      largeDesktop: { top: "18%", left: "5%" },
      extraLargeDesktop: { top: "18%", left: "5%" },
    },
    size: {
      desktop: { width: "180px", height: "140px" },
      tablet: { width: "165px", height: "130px" },
      largeDesktop: { width: "200px", height: "155px" },
      extraLargeDesktop: { width: "230px", height: "180px" },
    },
    parallaxFactor: 0.12,
    zIndex: 3,
  },
  {
    id: "restaurants",
    category: "Dining",
    location: "Top Restaurants",
    image: "/destinations/restaurant.jpg",
    rotation: 2,
    initialPosition: {
      desktop: { top: "60%", right: "5%" },
      tablet: { top: "62%", right: "2%" },
      largeDesktop: { top: "60%", right: "3%" },
      extraLargeDesktop: { top: "60%", right: "5%" },
    },
    size: {
      desktop: { width: "230px", height: "160px" },
      tablet: { width: "195px", height: "145px" },
      largeDesktop: { width: "250px", height: "175px" },
      extraLargeDesktop: { width: "280px", height: "195px" },
    },
    parallaxFactor: 0.2,
    zIndex: 1,
  },
];
